// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfCIjr5_NIHWzOxiGurFyEZcoIemi0j4',
    appId: '1:778988542916:web:3aaefa5396a6460b7e6291',
    messagingSenderId: '778988542916',
    projectId: 'inscribetec-44c30',
    authDomain: 'inscribetec-44c30.firebaseapp.com',
    storageBucket: 'inscribetec-44c30.firebasestorage.app',
    measurementId: 'G-N2CS5QWXN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOwI2XAs6Zk2D6efAedAuyLXYYp6ZmyM',
    appId: '1:778988542916:android:387afd539b5f2fd77e6291',
    messagingSenderId: '778988542916',
    projectId: 'inscribetec-44c30',
    storageBucket: 'inscribetec-44c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNy_LWQUmalfunCSQqpK_yUXKpDRQ590',
    appId: '1:778988542916:ios:3d5ebb43a55110a07e6291',
    messagingSenderId: '778988542916',
    projectId: 'inscribetec-44c30',
    storageBucket: 'inscribetec-44c30.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNy_LWQUmalfunCSQqpK_yUXKpDRQ590',
    appId: '1:778988542916:ios:3d5ebb43a55110a07e6291',
    messagingSenderId: '778988542916',
    projectId: 'inscribetec-44c30',
    storageBucket: 'inscribetec-44c30.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCfCIjr5_NIHWzOxiGurFyEZcoIemi0j4',
    appId: '1:778988542916:web:083b1a41801230dc7e6291',
    messagingSenderId: '778988542916',
    projectId: 'inscribetec-44c30',
    authDomain: 'inscribetec-44c30.firebaseapp.com',
    storageBucket: 'inscribetec-44c30.firebasestorage.app',
    measurementId: 'G-X661W3GC9R',
  );

}